// Páginas de SEO — el contenido, separado del armado (seo/armar.mjs).
//
// Por qué existen (26-sept-2026, Thiago: "quiero trabajar el SEO primero"):
// el panel es una SPA con rutas por numeral (#/demo). Google NO indexa lo que
// va después del #, así que para él todo recurrentesapp.com es UNA sola página,
// y encima el HTML le llega vacío porque el texto lo pinta React. Escribir
// contenido adentro de la SPA es tirar el trabajo: no hay dónde ponerlo.
//
// Estas páginas son HTML de verdad, con el texto adentro, cada una con su URL.
// Se sirven desde public/ (Vercel las encuentra antes que el catch-all de la
// SPA) y con cleanUrls quedan sin el .html.
//
// Para editar un texto: tocá acá y corré `npm run seo`. No se edita el HTML
// generado, que se pisa en cada corrida.

export const SITIO = "https://www.recurrentesapp.com";

// Cada página: slug (la URL), title y description (lo que se ve en Google),
// h1, intro, bloques de contenido y las preguntas del final.
export const PAGINAS = [
  {
    slug: "suscripciones-shopify",
    title: "Suscripciones en Shopify con Mercado Pago | Recurrentes",
    description: "Vendé por suscripción en tu Shopify cobrando con Mercado Pago. El cliente se suscribe una vez, se le cobra solo y la orden se crea sola en tu tienda. US$ 99 por mes más una comisión que baja cuando crecés.",
    h1: "Suscripciones en Shopify, cobrando con Mercado Pago",
    intro: "Shopify no tiene suscripciones con Mercado Pago. Las apps de suscripción del App Store cobran con Shopify Payments o Stripe, que en Argentina no le sirven a casi nadie. Recurrentes resuelve justo eso: tu cliente se suscribe en la ficha de producto y Mercado Pago le cobra cada período, con la plata cayendo en tu cuenta.",
    bloques: [
      { h: "Cómo funciona", p: "Pegás un snippet en tu tema y aparece el selector de packs en la página de producto: compra única o suscripción, con los descuentos y las frecuencias que definas. Cuando alguien se suscribe, Mercado Pago le cobra automáticamente en la fecha que corresponde y Recurrentes crea la orden paga en tu Shopify, con la dirección y el envío, lista para despachar." },
      { h: "Por qué Mercado Pago y no una tarjeta internacional", p: "En Argentina la mayoría de tus compradores paga con tarjeta local o con dinero en la cuenta de Mercado Pago. Una app que solo acepte Shopify Payments te deja afuera a la mayor parte del mercado. Recurrentes usa la cuenta de Mercado Pago que ya tenés, así que no cambiás de pasarela ni esperás acreditaciones nuevas." },
      { h: "Qué se puede configurar", p: "Packs de 1, 2 o 3 unidades con precio propio y precio tachado; el descuento por suscribirse; cada cuánto se repite el envío; regalos por pack; más de diez diseños del selector con los colores de tu marca; y los mails y mensajes de WhatsApp automáticos que le llegan a tu cliente con tu nombre, no con el nuestro." },
      { h: "Qué pasa con las órdenes y el stock", p: "Cada cobro aprobado genera una orden en tu Shopify igual que una compra normal: descuenta stock, dispara los mails de tu tienda y aparece en tus reportes. No hay planillas ni pedidos cargados a mano." },
    ],
    faq: [
      ["¿Necesito una app del App Store de Shopify?", "No. La conexión se hace con una app privada que creás vos en el panel de desarrolladores de Shopify, en dos pasos guiados. Si preferís, lo dejamos andando nosotros en una llamada."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso. Solo se cobra sobre lo que de verdad entró: lo que se rechaza o se devuelve no cuenta. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar, y se paga cuando ya está funcionando."],
      ["¿Mis clientes pueden cancelar solos?", "Sí. Cada suscriptor tiene un portal propio donde pausa, cambia la dirección o cancela sin escribirte."],
    ],
  },
  {
    slug: "suscripciones-tiendanube",
    title: "Suscripciones en Tiendanube con Mercado Pago | Recurrentes",
    description: "Cobrá suscripciones en tu Tiendanube con Mercado Pago, con packs, variantes y descuentos. El cobro es automático y la orden se crea sola.",
    h1: "Suscripciones en Tiendanube, con Mercado Pago",
    intro: "Tiendanube tiene suscripciones nativas, pero con límites que dejan afuera a muchas tiendas: solo funcionan con Pago Nube y tarjeta de crédito, piden plan Impulso o superior, no admiten variantes y solo permiten un producto con suscripción por carrito. Recurrentes cubre exactamente lo que queda afuera.",
    bloques: [
      { h: "Qué podés hacer que la suscripción nativa no permite", p: "Cobrar con la cuenta de Mercado Pago que ya usás, vender variantes (sabores, talles, colores), armar packs de varias unidades con precio propio, y tener más de un producto por suscripción en el mismo carrito." },
      { h: "Cómo se instala", p: "Instalás la app desde tu panel de Tiendanube y el selector aparece en la ficha de producto. Cada cobro de Mercado Pago genera la orden paga en tu tienda, con la dirección del cliente y el envío que corresponda." },
      { h: "Qué ve tu cliente", p: "En la misma página del producto elige entre comprar una vez o suscribirse, con el descuento y la frecuencia a la vista. Después recibe los avisos de cada cobro por mail y WhatsApp, con tu marca, y tiene un portal para pausar o cancelar cuando quiera." },
    ],
    faq: [
      ["¿Sirve si estoy en el plan más básico de Tiendanube?", "Sí. Recurrentes no depende del plan de Tiendanube ni de Pago Nube."],
      ["¿Puedo usar débito?", "Depende de lo que habilite Mercado Pago para suscripciones en tu cuenta. La suscripción nativa de Tiendanube solo acepta crédito."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar."],
    ],
  },
  {
    slug: "suscripciones-ecommerce",
    title: "Cómo vender por suscripción en tu ecommerce (Argentina) | Recurrentes",
    description: "Guía para pasar tu ecommerce a un modelo de suscripción en Argentina: qué productos sirven, cómo elegir la frecuencia y el descuento, y cómo se cobra en automático.",
    h1: "Cómo vender por suscripción en tu ecommerce",
    intro: "Si tus clientes te vuelven a comprar el mismo producto cada mes o cada dos, estás pagando publicidad dos veces por la misma venta. Una suscripción convierte esa recompra en algo que pasa solo. Esto es lo que hay que resolver para hacerlo en Argentina.",
    bloques: [
      { h: "Qué productos sirven", p: "Los que se consumen y se terminan en un plazo previsible: suplementos, café, cosmética, productos de limpieza, alimento para mascotas, higiene personal. La pregunta que ordena todo es cada cuánto se le acaba a tu cliente: esa es la frecuencia de la suscripción." },
      { h: "Qué descuento poner", p: "Entre 10% y 20% suele alcanzar. El cliente no se suscribe solo por el precio: se suscribe por no quedarse sin el producto. Un descuento más alto te come el margen sin mover la conversión, y encima te ata a venderle barato para siempre." },
      { h: "Cómo se cobra sin que hagas nada", p: "Con la suscripción de Mercado Pago. El cliente autoriza una vez el cobro recurrente y, en cada período, Mercado Pago le debita y avisa. Recurrentes escucha ese aviso y crea la orden en tu tienda, con dirección y envío, lista para despachar." },
      { h: "Qué mirar después", p: "Los tres números de una suscripción son cuántos se suman por mes, cuántos se van (churn) y cuánto factura cada uno antes de irse. Si se van más de los que entran, el problema casi nunca es el precio: es la frecuencia mal elegida o un producto que no se consume tan rápido como creías." },
    ],
    faq: [
      ["¿Necesito cambiar de plataforma?", "No. Funciona sobre tu Shopify o tu Tiendanube actual."],
      ["¿Y si mi producto no se consume?", "La suscripción no va a funcionar. Antes de armarla, mirá qué porcentaje de tus clientes ya te vuelve a comprar solo: si es menos del 10%, primero hay que trabajar la recompra."],
    ],
  },
  {
    slug: "alternativa-a-puentify",
    eyebrow: "Puentify · análisis honesto",
    title: "Puentify: buena opción para suscripciones en Argentina (y qué mirar) | Recurrentes",
    description: "Puentify es una buena opción para cobrar suscripciones en Shopify y Tiendanube con Mercado Pago. Qué hace bien, qué conviene mirar y cómo se compara con Recurrentes.",
    h1: "Puentify es una buena opción para suscripciones en Argentina",
    intro: "Puentify resuelve suscripciones en Shopify y Tiendanube cobrando con Mercado Pago, sin abono mensual, y tiene tiendas conocidas usándolo. Acá va qué hace bien, qué conviene mirar antes de decidir y, al final, en qué se diferencia Recurrentes.",
    bloques: [
      { h: "Lo que Puentify hace bien", p: "Funciona en Shopify y Tiendanube, cobra con Mercado Pago, tiene portal del cliente y no cobra abono mensual. Tiendas conocidas lo usan hace tiempo. Es una opción razonable para arrancar sin costo fijo." },
      { h: "Qué conviene mirar: el 2%", p: "Sin abono, cobra un porcentaje de cada venta (2%, según comercios que trabajan con ellos; no está publicado). Con poca facturación es barato; cuando la suscripción crece, ese 2% supera a cualquier abono." },
      { h: "Qué conviene mirar: packs, variantes y automatizaciones", p: "No permite suscribirse a una variante puntual ni dos productos con suscripción en el mismo carrito, y no trae diseños de widget ni mails con tu marca ni avisos por WhatsApp." },
      { h: "Dónde Recurrentes hace las cosas distinto", p: "Abono fijo de US$ 99 y una comisión que baja cuando crecés (1,8% · 1,5% · 1,3%). Packs con regalos, variantes, checkout y widget con tu marca, recupero de carritos por WhatsApp y mails propios. Todo en un panel." },
    ],
    vs: { titulo: "Puentify y Recurrentes, con los datos puestos", intro: "El setup y la comisión de Puentify no figuran en su web: salen de comercios que trabajan con ellos. El resto, de su sitio público.", nombre: "Puentify", fuente: "Datos verificados el 21 de septiembre de 2026 en puentify.app. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>USD 99/mes + 1,8%</b><small>el % baja a 1,5 y 1,3</small>", "Sin abono<small>solo comisión</small>"],
      ["Comisión sobre cada venta", "<b>0%</b>", "2%<small>de todo lo que cobrás</small>"],
      ["Cobra con Mercado Pago", "✓ Sí", "✓ Sí"],
      ["Funciona en Shopify y Tiendanube", "✓ Sí", "✓ Sí"],
      ["Suscribir una variante puntual", "✓ Sí", "✕ No"],
      ["Dos productos con suscripción en el mismo carrito", "✓ Sí", "✕ No"],
      ["Diseños de widget", "100% personalizables, con tus fotos", "✕ No"],
      ["Mails automáticos con tu marca", "✓ Sí", "✕ No"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "✕ No"],
      ["Portal del cliente", "✓ Sí", "✓ Sí"],
    ] },
    faq: [
      ["¿Cobran comisión por venta?", "Sí: US$ 99 por mes más un porcentaje de lo que cobrás, que baja a medida que crecés (1,8% · 1,5% · 1,3%). Se calcula sobre lo que de verdad se cobró, no sobre lo que facturaste en teoría."],
      ["¿Puedo migrar suscriptores que ya tengo en otra herramienta?", "Las autorizaciones de cobro de Mercado Pago no se transfieren entre aplicaciones: cada suscriptor tiene que volver a autorizar. Lo que sí se puede es acompañar esa migración con un flujo de mails para que no se te caiga nadie en el camino."],
    ],
  },

  // ── Mercado Pago: el término núcleo ──────────────────────────────────────
  {
    slug: "suscripciones-mercado-pago",
    title: "Suscripciones con Mercado Pago para tu tienda | Recurrentes",
    description: "Cómo cobrar suscripciones con Mercado Pago en tu ecommerce: qué se puede, qué tarjetas acepta, qué pasa si un cobro falla y cómo se conecta con Shopify o Tiendanube.",
    h1: "Suscripciones con Mercado Pago",
    intro: "Mercado Pago tiene cobro recurrente desde hace años, pero no viene enchufado a tu tienda: la API existe y nadie la usa por vos. Esto es lo que se puede hacer hoy y qué hace falta para que cada cobro termine en una orden despachada.",
    bloques: [
      { h: "Qué es una suscripción en Mercado Pago", p: "Es una autorización: tu cliente aprueba una vez que le cobres cada cierta cantidad de días, y desde ahí Mercado Pago debita solo, sin pedirle nada. No es un link de pago que se manda todos los meses ni una transferencia que hay que perseguir. La plata cae en tu cuenta de Mercado Pago, igual que cualquier venta." },
      { h: "Qué medios de pago acepta", p: "Tarjeta de crédito y, según lo que tenga habilitado tu cuenta, dinero disponible en la cuenta de Mercado Pago. El débito no siempre está disponible para cobro recurrente: es una decisión de Mercado Pago sobre cada cuenta, no de la tienda ni de la herramienta que uses." },
      { h: "Qué pasa cuando un cobro falla", p: "Mercado Pago reintenta por su cuenta durante unos días antes de dar la suscripción por caída. Lo importante es enterarte: el suscriptor queda marcado y le podés escribir para que cambie la tarjeta antes de perderlo. Sin eso, un rechazo se transforma en una baja silenciosa." },
      { h: "Lo que falta, y es donde entra Recurrentes", p: "Mercado Pago cobra, pero no sabe nada de tu tienda: no crea la orden, no descuenta stock, no arma el envío ni le avisa a tu cliente. Recurrentes escucha cada cobro aprobado y genera la orden paga en tu Shopify o Tiendanube con la dirección y el envío que corresponda." },
    ],
    faq: [
      ["¿Necesito una cuenta especial de Mercado Pago?", "No. Se usa la cuenta que ya tenés. Se conecta desde el panel en un clic."],
      ["¿La plata pasa por Recurrentes?", "Nunca. El cobro va de la tarjeta de tu cliente a tu cuenta de Mercado Pago, sin escalas. Nuestra comisión te la facturamos aparte, a fin de mes."],
      ["¿Mi cliente puede cancelar?", "Sí, desde su portal o desde su propia cuenta de Mercado Pago. Las dos formas quedan reflejadas en tu panel."],
    ],
  },
  {
    slug: "cobro-recurrente-mercado-pago",
    title: "Cobro recurrente en Mercado Pago: cómo funciona | Recurrentes",
    description: "Cada cuánto cobra, qué ve tu cliente, qué pasa con los rechazos y cómo se pausa o cancela un cobro recurrente de Mercado Pago.",
    h1: "Cómo funciona el cobro recurrente de Mercado Pago",
    intro: "Si ya decidiste vender por suscripción, lo que sigue son las preguntas del día a día: cuándo cae la plata, qué ve el cliente en su resumen y qué hacer cuando un cobro rebota. Esto es el mecanismo, sin vueltas.",
    bloques: [
      { h: "Cuándo se cobra", p: "El primer cobro sale en el momento en que el cliente autoriza. Los siguientes, cada N días contados desde ese día: si se suscribió un 12 con frecuencia de 30 días, el próximo cae el 11 o 12 del mes siguiente. No hay fecha fija de corte para todos: cada suscriptor tiene su propio calendario." },
      { h: "Qué ve tu cliente", p: "En su resumen de tarjeta aparece el nombre de tu cuenta de Mercado Pago, no el nuestro. Y en su cuenta de Mercado Pago ve la suscripción listada, con la opción de cancelarla cuando quiera. Eso no se puede evitar, y es sano: la alternativa es que desconozca el cargo y termine en un contracargo." },
      { h: "Qué hacer con un rechazo", p: "Casi siempre es una tarjeta vencida o sin límite, no un cliente que se quiere ir. Lo que recupera ese cobro es escribirle en el momento, con el link para actualizar la tarjeta. Recurrentes marca la suscripción como rechazada y dispara el aviso por mail y WhatsApp automáticamente." },
      { h: "Pausar en lugar de cancelar", p: "Cuando alguien quiere cortar, ofrecerle pausar uno o dos ciclos salva una parte de las bajas: el que se va de viaje o le sobró producto no quiere irse, quiere saltear un envío. La pausa deja la autorización viva y se reactiva sola en la fecha que elija." },
    ],
    faq: [
      ["¿Puedo cambiar el precio de una suscripción activa?", "Cambiar el monto de una autorización ya aprobada es limitado y arriesgado: lo más prolijo es dar de baja la vieja y ofrecer la nueva. Por eso conviene pensar bien el precio antes de lanzar."],
      ["¿Cuánto tarda en acreditarse?", "Lo mismo que cualquier venta tuya en Mercado Pago: depende del plazo de acreditación que tengas configurado en tu cuenta."],
    ],
  },
  {
    slug: "debito-automatico-para-mi-tienda",
    title: "Débito automático para tu tienda online | Recurrentes",
    description: "Cómo cobrarle automáticamente todos los meses a tus clientes sin ser una empresa de servicios: qué es, en qué se diferencia del débito bancario y cómo se activa.",
    h1: "Débito automático para tu tienda online",
    intro: "Muchos comerciantes lo buscan así: «quiero que se le debite solo». No hace falta ser una prepaga ni un gimnasio grande para tenerlo, y no es el débito automático del banco. Es más simple y lo activás vos.",
    bloques: [
      { h: "No es el débito automático del banco", p: "El débito en cuenta bancaria (CBU) lo tramita el banco, pide papeles y está pensado para servicios. Lo que usás en un ecommerce es una autorización de cobro recurrente sobre la tarjeta, a través de Mercado Pago. Se activa desde tu cuenta, sin trámite, y el cliente la aprueba en dos toques." },
      { h: "Qué necesitás para tenerlo", p: "Una cuenta de Mercado Pago y un producto que tu cliente consuma con cierta regularidad. Nada más. El cliente elige suscribirse en la ficha de producto y desde ahí se le cobra cada período." },
      { h: "Qué gana tu cliente y qué ganás vos", p: "Él deja de acordarse de volver a comprar y suele pagar un poco menos. Vos dejás de pagar publicidad dos veces por el mismo cliente y sabés cuánto vas a facturar el mes que viene. El ingreso deja de depender de cuánta gente entre hoy a tu tienda." },
    ],
    faq: [
      ["¿Le puedo cobrar sin que se entere?", "No, y no querrías: el cliente autoriza explícitamente y ve la suscripción en su cuenta de Mercado Pago. Un cargo que no reconoce termina en contracargo, que es peor que perder la venta."],
      ["¿Sirve para un servicio y no un producto?", "Sí. Gimnasios, clases y membresías usan el mismo mecanismo; lo único que cambia es que no hay envío."],
    ],
  },

  // ── Plataforma + Mercado Pago: las más específicas y las que más cierran ──
  {
    slug: "shopify-suscripciones-mercado-pago",
    title: "Shopify con suscripciones y Mercado Pago | Recurrentes",
    description: "Por qué las apps de suscripción de Shopify no sirven en Argentina y cómo cobrar suscripciones con Mercado Pago en tu tienda Shopify.",
    h1: "Shopify + suscripciones + Mercado Pago",
    intro: "Si buscaste una app de suscripciones en el App Store de Shopify ya te topaste con el problema: todas cobran con Shopify Payments o Stripe. En Argentina eso deja afuera a la mayoría de tus compradores. Acá va por qué pasa y cuál es la salida.",
    bloques: [
      { h: "Por qué las apps del App Store no te sirven", p: "Shopify tiene una API de suscripciones, pero está atada a las pasarelas que soportan cobro recurrente dentro de su ecosistema. Mercado Pago no es una de ellas. Por eso podés instalar la app, configurarla entera, y descubrir recién al final que no podés cobrar." },
      { h: "Cómo se resuelve", p: "El selector de suscripción va en la ficha de producto y el cobro se hace por fuera, con la suscripción de Mercado Pago. Cuando el cobro se aprueba, la orden se crea en tu Shopify como una compra paga normal: descuenta stock, dispara tus mails y aparece en tus reportes." },
      { h: "Qué ve tu cliente", p: "En la misma página del producto elige comprar una vez o suscribirse, con el descuento y la frecuencia a la vista, y los packs si los tenés. El botón de tu tema sigue funcionando para la compra suelta: no se reemplaza tu checkout, se suma una opción." },
      { h: "Qué hace falta de tu lado", p: "Conectar la tienda con una app privada que creás vos en el panel de desarrolladores de Shopify, conectar tu Mercado Pago y armar el plan. Si preferís no tocar nada, lo dejamos andando nosotros en una llamada de 15 minutos." },
    ],
    faq: [
      ["¿Pierdo Shop Pay o las cuotas?", "No. La compra única sigue pasando por el checkout de Shopify con todos los medios que ya tenías. Lo que cambia es solo la opción de suscripción."],
      ["¿Funciona con variantes?", "Sí: sabores, talles y colores, y también packs de varias unidades con precio propio."],
    ],
  },
  {
    slug: "tiendanube-suscripciones-mercado-pago",
    title: "Tiendanube con suscripciones y Mercado Pago | Recurrentes",
    description: "Las suscripciones nativas de Tiendanube solo funcionan con Pago Nube, crédito y plan Impulso. Cómo cobrar con Mercado Pago, con variantes y packs.",
    h1: "Tiendanube + suscripciones + Mercado Pago",
    intro: "Tiendanube sumó suscripciones nativas, y para algunas tiendas alcanzan. Para el resto, los límites aparecen rápido. Si chocaste con alguno, esto es lo que se puede hacer.",
    bloques: [
      { h: "Dónde están los límites de la nativa", p: "Funciona solo con Pago Nube y tarjeta de crédito, pide plan Impulso o superior, no admite variantes y solo deja un producto con suscripción por carrito. Si vendés sabores o talles, si querés cobrar con tu Mercado Pago, o si armás packs, quedás afuera por diseño." },
      { h: "Qué cambia con Recurrentes", p: "Cobrás con la cuenta de Mercado Pago que ya usás, vendés variantes, armás packs de varias unidades con precio y precio tachado propios, y podés tener más de un producto por suscripción. No depende de tu plan de Tiendanube." },
      { h: "Cómo se instala", p: "Instalás la app desde tu panel de Tiendanube y el selector aparece en la ficha de producto. Cada cobro aprobado crea la orden paga en tu tienda, con la dirección del cliente y el envío correspondiente." },
    ],
    faq: [
      ["¿Puedo tener las dos, la nativa y esta?", "Técnicamente sí, pero no conviene: dos selectores en la misma ficha confunden al comprador y no vas a saber cuál vendió."],
      ["¿Sirve en el plan más económico?", "Sí. No depende del plan de Tiendanube ni de Pago Nube."],
    ],
  },

  // ── Argentina ────────────────────────────────────────────────────────────
  {
    slug: "suscripciones-argentina",
    title: "Suscripciones en Argentina: qué se puede cobrar y con qué | Recurrentes",
    description: "Panorama de las suscripciones para negocios argentinos: qué pasarelas permiten cobro recurrente, qué plataformas lo soportan y qué queda afuera.",
    h1: "Suscripciones en Argentina: el panorama real",
    intro: "Vender por suscripción en Argentina tiene sus propias reglas, y casi todo lo que se lee en internet está escrito para otro mercado. Esto es lo que funciona acá, en septiembre de 2026.",
    bloques: [
      { h: "Con qué se cobra", p: "Mercado Pago es la opción realista: es donde ya está tu comprador y su API de suscripciones funciona. Stripe no abre cuentas a comercios argentinos, así que solo entra si tenés una sociedad afuera, y en ese caso cada tarjeta argentina te sale más cara por ser internacional. Las pasarelas locales alternativas están en distintos estados de madurez." },
      { h: "Qué plataformas lo soportan", p: "Shopify tiene API de suscripciones pero atada a pasarelas que no incluyen Mercado Pago. Tiendanube tiene suscripciones nativas con límites fuertes (solo Pago Nube, crédito, sin variantes). WooCommerce y Empretienda no traen nada nativo. En los cuatro casos, el cobro recurrente con Mercado Pago hay que resolverlo por fuera. Recurrentes funciona en las cuatro: Shopify y Tiendanube con app propia, WooCommerce y Empretienda con la conexión armada a medida en la puesta en marcha." },
      { h: "El problema que nadie menciona", p: "Cobrar es la mitad del trabajo. La otra mitad es que cada cobro se convierta en una orden en tu tienda, con stock, dirección y envío. Si eso no pasa solo, alguien va a cargar pedidos a mano todos los meses, y ahí la suscripción deja de ser un negocio y pasa a ser una tarea." },
      { h: "Qué mirar antes de elegir herramienta", p: "Cuánto cobra de comisión y sobre qué base; si soporta variantes y packs; si genera la orden sola; y qué pasa cuando un cobro se rechaza. Esas cuatro definen si escala o si te da trabajo." },
    ],
    faq: [
      ["¿Se puede cobrar con débito?", "Depende de lo que Mercado Pago habilite en tu cuenta para cobro recurrente. No es algo que decida la herramienta."],
      ["¿Necesito facturar distinto?", "Cada cobro es una venta como cualquier otra a efectos de facturación. Consultalo con tu contador según tu condición."],
    ],
  },
  {
    slug: "vender-por-suscripcion-argentina",
    title: "¿Te conviene vender por suscripción? Los números | Recurrentes",
    description: "Cuándo conviene pasar tu tienda a suscripción: qué tasa de recompra necesitás, cuánto descuento poner y cómo se mide si funciona.",
    h1: "¿Te conviene vender por suscripción?",
    intro: "La suscripción no sirve para todos los productos ni para todas las tiendas. Antes de armarla, estos son los números que dicen si vale la pena en tu caso. Si no dan, mejor saberlo ahora.",
    bloques: [
      { h: "El número que decide: tu recompra actual", p: "Mirá qué porcentaje de tus clientes ya te vuelve a comprar sin que hagas nada. Si es menos del 10%, la suscripción no va a arreglar eso: el problema está en el producto o en la experiencia, y una suscripción solo lo va a hacer más visible. Del 20% para arriba, tenés con qué trabajar: esa gente ya decidió que le sirve." },
      { h: "Qué descuento poner", p: "Entre 10% y 20% suele alcanzar. El cliente no se suscribe por el precio, se suscribe por no quedarse sin el producto. Un descuento más alto te come el margen sin mover la conversión, y te ata a venderle barato para siempre." },
      { h: "Cómo se mide si funciona", p: "Tres números: cuántos suscriptores entran por mes, cuántos se van (churn) y cuánto factura cada uno antes de irse. Si se van más de los que entran, casi nunca es el precio: es la frecuencia mal elegida. Le estás mandando producto antes de que termine el anterior." },
      { h: "Cuánto cuesta arrancar", p: "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar, y se paga cuando ya está funcionando." },
    ],
    faq: [
      ["¿Cuánto tarda en verse el resultado?", "El primer mes ves cuántos se suscriben. El número que importa —cuántos siguen— recién se ve en el tercer o cuarto cobro."],
      ["¿Y si me arrepiento?", "Las suscripciones activas siguen cobrándose; podés dejar de ofrecer nuevas cuando quieras. Nadie queda atado."],
    ],
  },
  {
    slug: "suscripciones-ecommerce-argentina",
    title: "Qué rubros funcionan con suscripción en Argentina | Recurrentes",
    description: "Suplementos, café, cosmética, mascotas y limpieza: qué rubros del ecommerce argentino funcionan con suscripción, con qué frecuencia y por qué.",
    h1: "Qué rubros funcionan con suscripción",
    intro: "La pregunta no es si tu rubro «puede» tener suscripción: es cada cuánto se le termina el producto a tu cliente. Si eso es previsible, funciona. Estos son los rubros donde mejor anda en Argentina y con qué frecuencia arrancar.",
    bloques: [
      { h: "Suplementos y vitaminas", p: "El caso más limpio: el envase dura exactamente lo que dice la etiqueta. Si son 60 cápsulas a dos por día, son 30 días. La frecuencia se calcula sola y el cliente entiende de inmediato por qué le conviene. Acá los packs de 2 y 3 meses funcionan muy bien." },
      { h: "Café y alimentos de consumo diario", p: "Entre 15 y 30 días según el tamaño. El riesgo es mandar de más: si el cliente acumula dos paquetes sin abrir, se da de baja. Conviene arrancar con la frecuencia más larga y dejar que él la acorte." },
      { h: "Cosmética y cuidado personal", p: "De 30 a 60 días, según el producto. Son rubros con mucha recompra pero también con mucha tentación de probar otra marca: acá el descuento por suscribirse y algún regalo en el primer envío hacen más diferencia que en otros rubros." },
      { h: "Mascotas y limpieza", p: "Alimento para mascotas es de los mejores: el consumo es constante y previsible, y quedarse sin es un problema real. Productos de limpieza funcionan parecido, con frecuencias más largas y packs grandes." },
      { h: "Dónde no funciona", p: "Indumentaria, electrónica, decoración y todo lo que se compra por impulso o por única vez. Si tu cliente no tiene una razón para necesitarlo otra vez en una fecha previsible, no hay suscripción que lo arregle." },
    ],
    faq: [
      ["¿Y si mi producto dura distinto según el cliente?", "Dejá que elija la frecuencia entre dos o tres opciones, y que pueda pausar. Eso resuelve casi toda la variación."],
      ["¿Conviene ofrecer packs?", "Sí. Un pack de 2 o 3 unidades sube lo que factura cada cliente y baja la cantidad de envíos, que es donde se te va el margen."],
    ],
  },

  // ── Competencia ──────────────────────────────────────────────────────────
  {
    slug: "puentify",
    eyebrow: "Puentify · qué es",
    title: "Puentify: qué es, cómo funciona y cuánto cuesta | Recurrentes",
    description: "Puentify es una app argentina para cobrar suscripciones en Shopify y Tiendanube con Mercado Pago. Qué ofrece, cómo cobra y qué mirar antes de elegir.",
    h1: "Puentify: qué es y cómo funciona",
    intro: "Puentify es una app argentina para vender por suscripción en Shopify y Tiendanube, cobrando con Mercado Pago. Es una buena opción y varias tiendas la usan. Acá va qué hace, cómo cobra y qué conviene tener en cuenta, para que decidas con los números puestos.",
    bloques: [
      { h: "Qué es Puentify", p: "Una app argentina para cobrar suscripciones en Shopify y Tiendanube con Mercado Pago. Se instala en tu tienda, el cliente se suscribe y Puentify genera los cobros y las órdenes." },
      { h: "Cómo cobra", p: "No tiene abono mensual: cobra un porcentaje de cada venta por suscripción (2%, según comercios que trabajan con ellos; no está publicado en su web). El setup tampoco está publicado." },
      { h: "Qué conviene mirar antes de elegir", p: "Cuánto cobra de comisión y sobre qué base; si funciona en tu plataforma; si soporta packs y variantes o solo un producto suelto; y si la orden se crea sola en tu tienda. Pedí ver las cuatro funcionando." },
      { h: "Cómo se compara con Recurrentes", p: "Recurrentes cobra abono fijo por suscriptores activos y 0% por venta, gratis hasta 10. Suma packs con regalos, variantes, widget y checkout con tu marca, mails propios y recupero de carritos por WhatsApp. Abajo la tabla con los datos públicos." },
    ],
    vs: { titulo: "Puentify y Recurrentes, con los datos puestos", intro: "El setup y la comisión de Puentify no figuran en su web: salen de comercios que trabajan con ellos. El resto, de su sitio público.", nombre: "Puentify", fuente: "Datos verificados el 21 de septiembre de 2026 en puentify.app. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>USD 99/mes + 1,8%</b><small>el % baja a 1,5 y 1,3</small>", "Sin abono<small>solo comisión</small>"],
      ["Comisión sobre cada venta", "<b>0%</b>", "2%<small>de todo lo que cobrás</small>"],
      ["Cobra con Mercado Pago", "✓ Sí", "✓ Sí"],
      ["Funciona en Shopify y Tiendanube", "✓ Sí", "✓ Sí"],
      ["Suscribir una variante puntual", "✓ Sí", "✕ No"],
      ["Dos productos con suscripción en el mismo carrito", "✓ Sí", "✕ No"],
      ["Diseños de widget", "100% personalizables, con tus fotos", "✕ No"],
      ["Mails automáticos con tu marca", "✓ Sí", "✕ No"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "✕ No"],
      ["Portal del cliente", "✓ Sí", "✓ Sí"],
    ] },
    faq: [
      ["¿Puedo probar antes de pagar?", "Sí. Es gratis hasta 10 suscriptores activos, así que podés validar con clientes reales antes de que te cueste un peso."],
      ["¿Puedo migrar suscriptores que ya tengo?", "Las autorizaciones de cobro de Mercado Pago no se transfieren entre aplicaciones: cada suscriptor tiene que volver a autorizar. Lo que sí se puede es acompañar la migración con mails automáticos para no perder gente en el camino."],
    ],
  },
  {
    slug: "puentify-precios",
    title: "Cuánto cuesta cobrar suscripciones: cómo comparar | Recurrentes",
    description: "Abono, comisión por venta e instalación: cómo comparar el costo real de una herramienta de suscripciones y cuánto cuesta Recurrentes.",
    h1: "Cuánto cuesta cobrar suscripciones (y cómo comparar)",
    intro: "Comparar precios de herramientas de suscripción es difícil porque cada una cobra distinto. Acá va cómo hacer la cuenta bien y cuánto cuesta Recurrentes, con los números puestos.",
    bloques: [
      { h: "El abono es la parte fácil de comparar", p: "Es un número fijo por mes. Lo que hay que mirar es de qué depende: si sube por cantidad de suscriptores, por facturación o por funciones. Un abono que sube con tus suscriptores es más justo al principio y más caro cuando funcionás; uno fijo es al revés." },
      { h: "La comisión por venta es donde se esconde la plata", p: "Mirá dos cosas: el porcentaje y sobre qué se calcula. No es lo mismo un 2% sobre todo lo facturado que un 1,8% sobre lo que de verdad entró, sin contar rechazos ni devoluciones. Y fijate si baja cuando crecés o se queda fijo para siempre." },
      { h: "La instalación", p: "Dejar el selector andando en un tema de Shopify, con packs y descuentos, lleva horas de trabajo real. Algunas herramientas te lo cobran, otras te lo dejan a vos. Ninguna de las dos está mal; lo que está mal es enterarte después." },
      { h: "Cuánto cuesta Recurrentes", p: "US$ 99 por mes, el mismo abono para todos, más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores activos, 1,5% de 301 a 1.000 y 1,3% arriba de eso. El porcentaje baja solo cuando llegás al tramo. La instalación es un pago único de USD 100 a 200, según lo que haya que armar, y se paga cuando está terminada y funcionando." },
    ],
    faq: [
      ["¿Por qué cobran por suscriptores y no un fijo?", "Porque al principio no tenés ninguno y no tiene sentido que pagues. Cuando pagás, ya te está entrando plata de esos suscriptores."],
      ["¿Hay costo por los mails y los WhatsApp?", "Los mails están incluidos. Los WhatsApp a tus clientes se cobran por mensaje, porque los cobra Meta; el precio está a la vista en el panel y viene apagado por defecto."],
    ],
  },

  // ── El problema, en criollo ──────────────────────────────────────────────
  {
    slug: "como-cobrar-todos-los-meses-a-mis-clientes",
    title: "Cómo cobrarle todos los meses a tus clientes | Recurrentes",
    description: "Dejá de perseguir la recompra: cómo hacer que tu cliente autorice un cobro mensual automático y que cada cobro se convierta en un pedido listo para despachar.",
    h1: "Cómo cobrarle todos los meses a tus clientes",
    intro: "Si tenés clientes que te compran lo mismo una y otra vez, y cada vez tenés que volver a venderles —el anuncio, el mensaje, el recordatorio—, esto es para vos. La venta se puede hacer una sola vez y repetirse sola.",
    bloques: [
      { h: "Lo que hacés hoy", p: "Pagás publicidad para traer al mismo cliente de nuevo. Le escribís por WhatsApp para recordarle que se le está por terminar. Conciliás transferencias a mano. Cargás el pedido otra vez. Y arrancás el mes sin saber cuánto vas a facturar." },
      { h: "Lo que cambia", p: "Tu cliente autoriza una vez que le cobres cada tanto. Desde ahí, Mercado Pago le debita en la fecha que corresponde y el pedido se crea solo en tu tienda, listo para despachar. Vos no tocás nada y él no tiene que acordarse de nada." },
      { h: "Por dónde se empieza", p: "Elegís un producto —el que más se repite— y definís cada cuánto se le termina al cliente y qué descuento le das por suscribirse. Con eso alcanza para lanzar. Lo demás se ajusta con los primeros suscriptores." },
      { h: "Qué pasa si se quiere ir", p: "Cancela desde su portal, sin escribirte. Suena mal y es lo contrario: la alternativa es que desconozca el cargo en la tarjeta, que es peor para vos. Y antes de la baja se le puede ofrecer pausar un ciclo, que recupera a una buena parte." },
    ],
    faq: [
      ["¿Tengo que cambiar de plataforma?", "No. Funciona sobre tu Shopify o tu Tiendanube actual."],
      ["¿Cuánto tarda en estar andando?", "La puesta en marcha la hacemos nosotros y suele quedar lista el mismo día que nos das los accesos."],
    ],
  },
  {
    slug: "suscripciones-sin-comision-por-venta",
    title: "Cuánto cuesta cobrar por suscripción | Recurrentes",
    description: "Cuánto te cuesta realmente una comisión del 1% o 2% sobre tus suscripciones, y por qué en Recurrentes solo pagás el abono.",
    h1: "Cuánto te cuesta cobrar por suscripción",
    intro: "Casi todas las herramientas de suscripción cobran un porcentaje de cada cobro, además del abono mensual. Suena a poco hasta que lo multiplicás por doce meses y por la cantidad de clientes que querés tener.",
    bloques: [
      { h: "La cuenta que conviene hacer", p: "Tomá tu ticket promedio, multiplicalo por la cantidad de suscriptores que querés tener en un año, y sacale el porcentaje. Con 100 suscriptores que pagan 30.000 pesos por mes, un 2% son 60.000 pesos mensuales. Al año, 720.000 pesos que se van sin que nadie haga nada nuevo por vos." },
      { h: "Por qué la comisión duele más que el abono", p: "El abono es previsible y lo podés presupuestar. La comisión crece exactamente cuando te está yendo bien, así que te castiga el éxito: cuanto mejor vendés, más pagás, aunque el trabajo de la herramienta sea el mismo con 10 que con 500 suscriptores." },
      { h: "Qué cobramos nosotros", p: "El abono, y nada más. US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso. Cero por ciento de cada venta, siempre. La única otra cosa es la instalación: un pago único de USD 100 a 200, según lo que haya que armar." },
      { h: "Lo que sí te va a cobrar alguien", p: "Mercado Pago cobra su comisión por procesar el pago, como en cualquier venta tuya. Eso no lo evita ninguna herramienta y no pasa por nosotros: es la relación entre tu cuenta y Mercado Pago." },
    ],
    faq: [
      ["¿Hay costos ocultos?", "Los WhatsApp a tus clientes se cobran por mensaje porque los cobra Meta, vienen apagados y el precio está a la vista en el panel. Los mails están incluidos."],
      ["¿El precio sube si vendo más caro?", "No. Depende de cuántos suscriptores activos tengas, no de cuánto factures."],
    ],
  },

  // ── Competidores (27-sept-2026). Fácil Uno queda afuera a pedido de Thiago. ──
  {
    slug: "alternativa-a-orquesty",
    eyebrow: "Orquesty · análisis honesto",
    title: "Orquesty: buena opción para suscripciones en Shopify (y qué mirar) | Recurrentes",
    description: "Orquesty es una buena plataforma de suscripciones para Shopify en Latam: cobra con Mercado Pago y tiene portal del suscriptor. Qué hace bien, qué conviene mirar y cómo se compara con Recurrentes.",
    h1: "Orquesty es una buena opción para suscripciones en Shopify",
    intro: "Si tu tienda está en Shopify y querés cobrar suscripciones con Mercado Pago, Orquesty es de las opciones serias de la región: equipo en Latam, portal del suscriptor y bundles. Acá va qué hace bien, qué conviene mirar antes de decidir y, al final, dónde Recurrentes hace las cosas distinto.",
    imagen: "/landing/panel-suscripciones.jpg", imagenLabel: "recurrentesapp.com · Suscripciones",
    bloques: [
      { h: "Lo que Orquesty hace bien", p: "Cobra con Mercado Pago, tiene portal del suscriptor con pausa, cancelación y cambio de dirección, bundles y cajas armadas, y un equipo en Latam que hace la implementación con vos. Para una tienda Shopify que quiere arrancar acompañada, es una opción seria." },
      { h: "Qué conviene mirar: el porcentaje", p: "Publica USD 79, 169 o 229 por mes más 2%, 1,5% o 1% sobre las ventas por suscripción. Ese porcentaje es lo que más pesa cuando crecés: con $2.000.000 por mes en suscripciones, un 1,5% son $30.000 todos los meses, además del abono." },
      { h: "Qué conviene mirar: solo Shopify", p: "Orquesty se instala como app personalizada en Shopify. Si tu tienda está en Tiendanube, o pensás mudarte, no es para vos." },
      { h: "Dónde Recurrentes hace las cosas distinto", p: "Abono fijo por suscriptores activos y 0% por venta. Shopify y Tiendanube con el mismo panel. Mails con tu marca y recupero de carritos por WhatsApp incluidos, sin Klaviyo. Y diseños de widget 100% personalizables con tus fotos." },
    ],
    vs: { titulo: "Orquesty y Recurrentes, con los datos puestos", intro: "Datos públicos de cada uno. Lo que Orquesty no documenta, no lo inventamos.", nombre: "Orquesty", fuente: "Datos verificados el 26 de septiembre de 2026 en orquesty.com. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>US$ 99 + comisión</b><small>después desde USD 99/mes</small>", "USD 79 a 229 por mes<small>según el plan</small>"],
      ["Comisión sobre cada venta", "<b>0%</b>", "1% a 2%<small>de las ventas por suscripción</small>"],
      ["Cobra con Mercado Pago", "✓ Sí", "✓ Sí"],
      ["Funciona en Shopify", "✓ Sí", "✓ Sí"],
      ["Funciona en Tiendanube", "✓ Sí", "✕ No"],
      ["Diseños de widget", "100% personalizables, con tus fotos", "3 modos<small>toggle, selector, suscripción primero</small>"],
      ["Mails automáticos con tu marca", "✓ Sí, incluidos", "Vía Klaviyo o Mailchimp<small>integración aparte</small>"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "No lo documenta"],
      ["Portal del cliente", "✓ Sí", "✓ Sí"],
    ] },
    faq: [
      ["¿Puedo migrar mis suscriptores desde Orquesty?", "Los planes los migramos nosotros en la misma llamada. Las suscripciones activas se dan de alta de nuevo con el cliente, porque la tarjeta la guarda cada plataforma en Mercado Pago."],
      ["¿Recurrentes también se instala como app personalizada?", "En Shopify se conecta con una app privada que creás vos en dos pasos guiados, o la dejamos andando nosotros. En Tiendanube se instala desde su tienda de apps."],
      ["¿Cuánto cuesta Recurrentes?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso, con todo incluido. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar, cuando ya está funcionando."],
    ],
  },
  {
    slug: "alternativa-a-reval",
    eyebrow: "Reval · análisis honesto",
    title: "Reval: buena opción para suscripciones con Mercado Pago en Shopify | Recurrentes",
    description: "Reval cobra suscripciones con Mercado Pago en Shopify y lo hace bien. Qué ofrece, qué conviene mirar (comisión sobre cada cobro, sin Tiendanube) y cómo se compara con Recurrentes.",
    h1: "Reval es una buena opción para suscripciones en Shopify",
    intro: "Reval fue de los primeros en resolver suscripciones con Mercado Pago dentro de Shopify, y sigue siendo una opción sólida. Acá va qué hace bien, qué conviene mirar antes de decidir y, al final, en qué se diferencia Recurrentes.",
    imagen: "/landing/panel-cobros.jpg", imagenLabel: "recurrentesapp.com · Cobros",
    bloques: [
      { h: "Lo que Reval hace bien", p: "Cobra con Mercado Pago dentro de Shopify, tiene portal del suscriptor y mails automáticos, y lleva tiempo en el mercado. Si estás en Shopify y querés algo probado, es una opción sólida." },
      { h: "Qué conviene mirar: la comisión", p: "Reval publica entre 1,2% y 1,8% de todo lo que cobrás, además de USD 99 a 249 por mes. Cuanto más vendés, más pagás. Hacé la cuenta con tu facturación real antes de firmar." },
      { h: "Qué conviene mirar: Tiendanube y variantes", p: "No funciona en Tiendanube (te proponen pasar a Shopify) y no permite suscribirse a una variante puntual ni llevar dos productos con suscripción en el mismo carrito." },
      { h: "Dónde Recurrentes hace las cosas distinto", p: "Abono fijo de US$ 99 y una comisión que baja cuando crecés. Shopify y Tiendanube. Variantes, dos productos en el carrito, packs con regalos, recupero de carritos por WhatsApp y checkout con tu marca. Todo incluido." },
    ],
    vs: { titulo: "Reval y Recurrentes, con los datos puestos", intro: "Datos públicos de cada uno. Lo que Reval no documenta, no lo inventamos.", nombre: "Reval", fuente: "Datos verificados el 21 de septiembre de 2026 en appreval.com. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>US$ 99 + comisión</b><small>después desde USD 99/mes</small>", "USD 99 a 249 por mes<small>según el plan</small>"],
      ["Comisión sobre cada venta", "<b>0%</b>", "1,2% a 1,8%<small>de todo lo que cobrás</small>"],
      ["Cobra con Mercado Pago", "✓ Sí", "✓ Sí"],
      ["Funciona en Shopify", "✓ Sí", "✓ Sí"],
      ["Funciona en Tiendanube", "✓ Sí", "✕ No<small>te hacen pasar a Shopify</small>"],
      ["Suscribir una variante puntual", "✓ Sí", "✕ No"],
      ["Dos productos con suscripción en el mismo carrito", "✓ Sí", "✕ No"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "✕ No"],
      ["Portal del cliente", "✓ Sí", "✓ Sí"],
    ] },
    faq: [
      ["¿Qué pasa con mis suscriptores actuales de Reval?", "Migramos los planes en la llamada de puesta en marcha. Las suscripciones activas se vuelven a dar de alta con cada cliente, con un mail o WhatsApp con su link."],
      ["¿Recurrentes cobra con la misma cuenta de Mercado Pago?", "Sí, con la que ya usás. Se conecta desde el panel en un clic y la plata entra en tu cuenta como cualquier venta."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso, todo incluido. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar, cuando ya está andando."],
    ],
  },
  {
    slug: "alternativa-a-recharge",
    eyebrow: "Recharge · análisis honesto",
    title: "Recharge: la app de suscripciones más grande de Shopify (y cómo funciona en Argentina) | Recurrentes",
    description: "Recharge es la referencia mundial en suscripciones para Shopify. Qué hace muy bien, por qué en Argentina choca con Mercado Pago y el idioma, y cómo se compara con Recurrentes.",
    h1: "Recharge es la referencia en suscripciones para Shopify",
    intro: "Recharge es la app de suscripciones más usada del mundo Shopify, con años de producto y funciones para tiendas enormes. Vale la pena conocerla. Acá va qué hace muy bien, qué pasa cuando la querés usar desde Argentina y, al final, qué hace Recurrentes distinto.",
    imagen: "/landing/panel-planes.jpg", imagenLabel: "recurrentesapp.com · Planes",
    bloques: [
      { h: "Lo que Recharge hace muy bien", p: "Es la app más completa del ecosistema Shopify: años de producto, integraciones con todo, herramientas para tiendas enormes y una comunidad gigante. Si vendés en Estados Unidos o Europa, es la referencia." },
      { h: "Qué pasa desde Argentina", p: "Cobra con Shopify Payments o Stripe, que no operan para comercios argentinos. Sin Mercado Pago, tus clientes no pueden pagar como pagan siempre. Los mails salen en inglés y el soporte también." },
      { h: "Qué conviene mirar: el precio", p: "USD 99 a 499 por mes más 1,49% + USD 0,19 por cada transacción. En dólares y por cobro, con una tienda argentina la cuenta se hace pesada rápido." },
      { h: "Dónde Recurrentes hace las cosas distinto", p: "Nació para el ecommerce argentino: Mercado Pago, castellano, soporte por WhatsApp, Shopify y Tiendanube, y una comisión más baja que la de afuera. No tenemos todo lo que tiene Recharge; tenemos lo que una tienda de acá usa." },
    ],
    vs: { titulo: "Recharge y Recurrentes, con los datos puestos", intro: "Datos públicos de cada uno. Recharge es excelente en su mercado; esto es lo que cambia desde Argentina.", nombre: "Recharge", fuente: "Datos verificados el 21 de septiembre de 2026 en getrecharge.com/pricing. Recharge compró Skio en abril de 2026. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>US$ 99 + comisión</b><small>después desde USD 99/mes</small>", "USD 99 a 499 por mes<small>según el plan</small>"],
      ["Comisión sobre cada venta", "<b>0%</b>", "1,49% + USD 0,19<small>por transacción</small>"],
      ["Cobra con Mercado Pago", "✓ Sí", "✕ No"],
      ["Funciona en Tiendanube", "✓ Sí", "✕ No"],
      ["Mails automáticos con tu marca", "✓ Sí, en castellano", "Sí<small>en inglés</small>"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "✕ No"],
      ["Soporte en español por WhatsApp", "✓ Sí", "✕ No"],
    ] },
    faq: [
      ["¿Recharge funciona en Argentina?", "Se instala, pero cobra con Shopify Payments o Stripe, que no operan para comercios argentinos. Sin Mercado Pago, tus clientes no pueden pagar como pagan siempre."],
      ["¿Recurrentes tiene lo mismo que Recharge?", "Lo que una tienda argentina usa: packs, descuentos, portal del cliente, pausas, cambio de dirección, mails y WhatsApp, y la orden creada en la tienda. No tenemos integraciones con Klaviyo ni herramientas para Shopify Plus."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso, todo incluido. La puesta en marcha es un pago único de USD 100 a 200, según lo que haya que armar."],
    ],
  },
  // ── Verticales: una página por rubro, con el producto de ejemplo ──
  {
    slug: "suscripcion-de-cafe",
    eyebrow: "Club de café",
    title: "Cómo armar un club de café por suscripción en tu tienda online | Recurrentes",
    description: "Vendé café de especialidad por suscripción: bolsas por mes, descuento por suscribirse, tueste de la semana y cobro automático con Mercado Pago en Shopify o Tiendanube.",
    h1: "Tu café, todos los meses, sin volver a vender",
    intro: "El café es el producto perfecto para la suscripción: se termina, se compra siempre igual y el cliente valora que le llegue recién tostado. Así lo arman las tostadoras que venden con Recurrentes.",
    imagen: "/landing/prod-cafe.jpg", imagenLabel: "Tostado · tienda de ejemplo", imagenFoto: true,
    bloques: [
      { h: "Packs por cantidad de bolsas", p: "1, 2 o 4 bolsas de 250 g por mes, cada pack con su precio y su descuento. El de 2 suele ser el más elegido; el de 4 el de mejor precio por unidad. El cliente lo ve en la misma ficha del producto." },
      { h: "Molienda y origen como variantes", p: "El cliente se suscribe a la variante exacta: grano, filtro o espresso; Colombia o Brasil. Cada cobro crea el pedido con esa variante, así el tostador sabe qué moler." },
      { h: "Tostado de la semana", p: "El cobro cae el mismo día de cada mes y la orden aparece en tu tienda: tostás el lunes, despachás en la semana. El cliente recibe el aviso por WhatsApp con el seguimiento." },
      { h: "Pausar cuando viaja", p: "Desde su portal el cliente pausa un mes, cambia la dirección o cancela. Sin escribirte. Es lo que más baja la cancelación en café." },
    ],
    capturas: [["/landing/panel-planes.jpg", "Planes"], ["/landing/panel-suscripciones.jpg", "Suscripciones"], ["/landing/panel-portal.jpg", "Portal del cliente"]],
    faq: [
      ["¿Puedo tener una página solo de suscripción?", "Sí. Además del widget en la ficha, armamos una landing de suscripción con tu marca: beneficios, bundle y preguntas. Mirá la tienda de ejemplo Tostado en recurrentesapp.com/demos/tostado."],
      ["¿Qué descuento conviene?", "Entre 10% y 15% por suscribirse, más un poco por pack. El cliente tiene que ver que le conviene claramente frente a comprar suelto."],
      ["¿Funciona con envío gratis desde un monto?", "Sí. Los envíos se cotizan con los correos que ya tenés en tu tienda, con las mismas reglas de envío gratis."],
    ],
  },
  {
    slug: "suscripcion-de-suplementos",
    eyebrow: "Suplementos y vitaminas",
    title: "Suscripción de suplementos y vitaminas en tu ecommerce | Recurrentes",
    description: "Vendé suplementos por suscripción: el envase dura 30 días, el cobro cae cada 30 días y el pedido se crea solo en tu Shopify o Tiendanube. Cobro con Mercado Pago, comisión que baja cuando crecés.",
    h1: "Suplementos por suscripción: el caso más limpio",
    intro: "Si son 60 cápsulas a dos por día, son 30 días. La frecuencia se calcula sola, el cliente entiende de inmediato por qué le conviene y vos dejás de depender de que se acuerde de recomprar.",
    imagen: "/landing/prod-supl.jpg", imagenLabel: "Nodo · tienda de ejemplo", imagenFoto: true,
    bloques: [
      { h: "Frecuencia igual a la duración del envase", p: "Un frasco de 30 días, cada 30 días. Un pack de 3, cada 90. El cliente elige el pack y la frecuencia queda armada; nunca le sobra ni le falta producto." },
      { h: "Descuento por suscribirse y por pack", p: "10% por suscribirse y un poco más en el pack de 3. Con precio tachado y etiqueta de más elegido en la ficha, como las mejores tiendas del rubro." },
      { h: "Pago rechazado, sin perder al cliente", p: "Cuando una tarjeta falla, Mercado Pago reintenta y el cliente recibe un WhatsApp con el link para cambiarla. La entrega no se corta y vos lo ves en el panel." },
      { h: "Dos productos en la misma suscripción", p: "Magnesio y vitamina D en el mismo carrito, cada uno con su frecuencia. Y extras que el cliente suma desde el checkout." },
    ],
    faq: [
      ["¿Sirve para productos con receta o control?", "Recurrentes no vende: crea la suscripción y el pedido. Las reglas de venta de tu producto siguen siendo las de tu tienda."],
      ["¿Puedo cambiar el precio a los que ya están suscriptos?", "Mercado Pago mantiene el monto autorizado. Desde el panel podés repreciar una suscripción cuando haga falta."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso."],
    ],
  },
  {
    slug: "suscripcion-alimento-para-mascotas",
    eyebrow: "Alimento para mascotas",
    title: "Suscripción de alimento para mascotas: que nunca falte | Recurrentes",
    description: "Vendé alimento balanceado por suscripción en tu tienda online: bolsas por mes, descuento por suscribirse, cobro automático con Mercado Pago y el pedido creado en Shopify o Tiendanube.",
    h1: "Alimento para mascotas por suscripción: que nunca falte",
    intro: "El perro come todos los días y la bolsa se termina siempre en la misma fecha. Es el producto donde la suscripción se siente menos como una venta y más como un favor al cliente.",
    imagen: "/landing/prod-pet.jpg", imagenLabel: "Patitas · tienda de ejemplo", imagenFoto: true,
    bloques: [
      { h: "Bolsas por mes según el tamaño", p: "1 bolsa de 3 kg para perros chicos, 2 o 3 para grandes. Cada pack con su precio; el cliente elige y la frecuencia se acomoda." },
      { h: "Regalo en el primer envío", p: "Un snack o un juguete en la primera orden, vinculado a un producto real de tu tienda: viaja en el pedido a $0 y el cliente lo ve en el widget." },
      { h: "La orden con dirección y envío", p: "Cada cobro crea el pedido en tu tienda con la dirección del cliente y el correo que eligió. Si se muda, cambia la dirección desde su portal y el próximo sale a la nueva." },
      { h: "Avisos por WhatsApp", p: "Próximo cobro, pedido en camino y, si dejó el carrito sin pagar, el recupero. Con el nombre de tu tienda." },
    ],
    faq: [
      ["¿Se puede cambiar el sabor sin cancelar?", "El cliente pausa y se vuelve a suscribir a la variante nueva desde tu ficha; el pack no se modifica una vez activo, para que nunca haya sorpresas en el cobro."],
      ["¿Qué pasa si el cliente se queda sin stock de mi lado?", "La orden se crea igual en tu tienda y la ves marcada; la despachás cuando repongas, como con cualquier venta."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso."],
    ],
  },
  {
    slug: "suscripcion-cosmetica-skincare",
    eyebrow: "Cosmética y skincare",
    title: "Suscripción de cosmética y skincare en tu tienda online | Recurrentes",
    description: "Vendé sérums, cremas y rutinas por suscripción: frecuencia según lo que dura cada producto, descuento por suscribirse y cobro automático con Mercado Pago. comisión que baja cuando crecés.",
    h1: "Tu rutina, en automático",
    intro: "Un sérum dura dos meses; una crema, uno. La suscripción convierte esa rutina en un cobro cada tanto y un envío que llega antes de que se termine. Y el cliente deja de irse a la góndola.",
    imagen: "/landing/prod-skin.jpg", imagenLabel: "Ámbar · tienda de ejemplo", imagenFoto: true,
    bloques: [
      { h: "Frecuencias distintas por producto", p: "El sérum cada 60 días, la crema cada 30. Cada plan tiene su frecuencia y el cliente puede llevar los dos en el mismo carrito." },
      { h: "Checkout con tu marca", p: "Colores, logo, tipografía y textos tuyos. Cupones que valen para toda la suscripción y envíos cotizados en vivo." },
      { h: "Retención antes de cancelar", p: "Cuando alguien quiere cancelar, primero le ofrecés pausar uno, dos o tres meses o un descuento en el próximo cobro. Acá es donde más bajas se evitan." },
      { h: "Diseño a la altura de tu marca", p: "Trece diseños de widget 100% personalizables con tus fotos, para que la suscripción se vea como el resto de tu tienda." },
    ],
    faq: [
      ["¿Mis clientes pueden cambiar de producto?", "Pausan y se suscriben al nuevo desde la ficha. El pack activo no se modifica para que el cobro sea siempre el que aceptaron."],
      ["¿Funciona con Tiendanube?", "Sí, y con Shopify. Cobrando con tu Mercado Pago."],
      ["¿Cuánto cuesta?", "US$ 99 por mes más una comisión de lo que cobrás: 1,8% hasta 300 suscriptores, 1,5% hasta 1.000 y 1,3% arriba de eso."],
    ],
  },
  // ── Guías de intención (qué busca la gente antes de comprar) ──
  {
    slug: "recuperar-carritos-abandonados-suscripcion",
    eyebrow: "Carritos abandonados",
    title: "Cómo recuperar carritos abandonados de suscripción por WhatsApp | Recurrentes",
    description: "El cliente dejó sus datos en el checkout y no pagó. Recurrentes le manda un WhatsApp a la hora y un mail a las 24 h con su carrito guardado. Es lo que más plata recupera.",
    h1: "El carrito sin pagar vuelve solo",
    intro: "De cada diez que empiezan a suscribirse, tres o cuatro no terminan. Recurrentes guarda el checkout y le escribe al cliente por WhatsApp y por mail, con el nombre de tu tienda, para que lo retome en un toque.",
    imagen: "/landing/panel-carritos.jpg", imagenLabel: "recurrentesapp.com · Carritos abandonados",
    bloques: [
      { h: "WhatsApp a la hora", p: "Si dejó el mail o el teléfono y no pagó, a la hora recibe un WhatsApp corto con su link. Si paga antes, no se manda. El texto ya está aprobado por Meta." },
      { h: "Mail a las 24 horas", p: "Un mail con tu marca, el producto y el descuento por suscribirse. Sale desde nuestros servidores, sin configurar nada." },
      { h: "Lo ves en el panel", p: "La pestaña Carritos abandonados lista cada checkout sin pagar, cuándo fue el último contacto y cuáles se recuperaron. Y cuánta plata." },
      { h: "Cuánto cuesta", p: "El mail está incluido. El WhatsApp se cobra por mensaje, centavos de dólar, y vos prendés o apagás cada flujo." },
    ],
    capturas: [["/landing/panel-carritos.jpg", "Carritos abandonados"], ["/landing/panel-flujos-whatsapp.jpg", "Flujos de WhatsApp"], ["/landing/panel-flujos-email.jpg", "Flujos de email"]],
    faq: [
      ["¿Desde qué número sale el WhatsApp?", "Desde el número de Recurrentes, a nombre de tu tienda. No tenés que conectar tu WhatsApp ni tener API propia."],
      ["¿El cliente puede pedir que no le escriban más?", "Sí, responde BAJA y no recibe más avisos. Está en cada mensaje."],
      ["¿Cuánto se recupera?", "Depende del rubro y del descuento. Las tiendas que lo tienen prendido recuperan una parte relevante de los carritos: cada uno es una suscripción que cobra todos los meses."],
    ],
  },
  {
    slug: "portal-del-suscriptor",
    eyebrow: "Portal del cliente",
    title: "Portal del suscriptor: pausar, cambiar dirección y cancelar sin soporte | Recurrentes",
    description: "Cada suscriptor tiene un portal con el link que recibe por mail y WhatsApp: pausa, cambia la dirección o la tarjeta y cancela solo. Vos decidís qué puede hacer.",
    h1: "Que el cliente se maneje solo",
    intro: "El 80% de los mensajes de soporte de una tienda con suscripciones son pausar, cambiar la dirección o cancelar. El portal del suscriptor lo resuelve sin que te escriban, y con un flujo de retención antes de cancelar.",
    imagen: "/landing/panel-portal.jpg", imagenLabel: "recurrentesapp.com · Portal del cliente",
    bloques: [
      { h: "Pausar y reactivar", p: "Salta los próximos cobros y la retoma cuando quiere. Ideal para vacaciones o cuando todavía tiene producto." },
      { h: "Cambiar dirección y tarjeta", p: "La dirección nueva se usa desde el próximo pedido. La tarjeta se cambia con el link de Mercado Pago, sin volver a suscribirse." },
      { h: "Cancelar con retención", p: "Antes del botón final, el cliente elige un motivo y ve alternativas: pausar uno, dos o tres meses, o un descuento en el próximo cobro. Vos ves los motivos en el panel." },
      { h: "Vos decidís qué habilitar", p: "Cada acción se prende o apaga desde Configuración → Portal. Lo que apagues, el cliente lo pide por mail." },
    ],
    capturas: [["/landing/panel-portal.jpg", "Portal del cliente"], ["/landing/panel-retencion.jpg", "Retención"], ["/landing/panel-suscripciones.jpg", "Suscripciones"]],
    faq: [
      ["¿El cliente necesita crear una cuenta?", "No. Entra con el link firmado que recibe en cada mail y WhatsApp. Sin contraseña."],
      ["¿Puede cambiar el pack desde el portal?", "No, a propósito: el pack que aceptó es el que se cobra. Para cambiarlo, pausa y se suscribe al nuevo desde tu ficha."],
      ["¿Se puede poner con mis colores?", "Sí, en Configuración → Portal → Apariencia."],
    ],
  },
  {
    slug: "meta-ads-suscripciones-conversions-api",
    eyebrow: "Meta Ads",
    title: "Meta Ads para vender suscripciones: Conversions API y eventos del checkout | Recurrentes",
    description: "Conectás tu pixel y Recurrentes manda AddToCart, InitiateCheckout y Purchase por la Conversions API, deduplicados y con el monto real. Meta aprende quién se suscribe.",
    h1: "Tu pixel se entera de cada suscripción",
    intro: "Si vendés suscripciones con pauta, Meta tiene que saber cuándo alguien se suscribe, no solo cuándo compra una vez. Recurrentes le manda los eventos del checkout desde el servidor, así nada se pierde por bloqueadores ni por iOS.",
    imagen: "/landing/panel-analiticas.jpg", imagenLabel: "recurrentesapp.com · Analíticas",
    bloques: [
      { h: "Tres eventos, del servidor", p: "AddToCart al abrir el checkout, InitiateCheckout al dejar el mail y Purchase al pagar, con el valor real del pack. Van por la Conversions API y también desde el navegador, deduplicados por event_id." },
      { h: "Optimizá por suscriptores", p: "Con Purchase bien reportado podés pedirle a Meta que optimice por compras de suscripción, que valen muchas veces más que una venta suelta." },
      { h: "Sin configurar nada raro", p: "Pegás el ID del pixel y el token en Integraciones. Listo. El resto lo hace Recurrentes en cada checkout." },
      { h: "Todo lo demás también", p: "Los mismos eventos alimentan tus públicos: quien dejó el carrito, quien pagó, quien canceló." },
    ],
    faq: [
      ["¿Sirve con el pixel que ya tengo en Shopify?", "Sí. Es el mismo pixel; Recurrentes le suma los eventos del checkout de suscripción, que Shopify no ve porque el checkout es nuestro."],
      ["¿Se duplican los eventos con los del navegador?", "No. Van con el mismo event_id y Meta se queda con uno."],
      ["¿Y Google Ads?", "Hoy los eventos van a Meta. Google Ads está en el radar."],
    ],
  },
  {
    slug: "que-es-la-recurrencia-en-ecommerce",
    eyebrow: "Recurrencia",
    title: "Qué es la recurrencia en ecommerce y cómo se convierte en suscripción | Recurrentes",
    description: "Recurrencia es cuando el mismo cliente vuelve a comprar el mismo producto. Cómo medirla en tu tienda, qué productos la tienen y cómo pasarla a suscripción con cobro automático.",
    h1: "Recurrencia: el cliente que vuelve solo",
    intro: "Si en tu tienda hay clientes que compran el mismo producto cada 30 o 60 días, ya tenés recurrencia. Lo que no tenés es el cobro automático: cada vez dependés de que se acuerden, vuelvan y no se vayan a otro lado.",
    bloques: [
      { h: "Cómo medirla", p: "En tu tienda, filtrá los clientes con dos o más pedidos y mirá cuánto pasa entre uno y otro. Si hay un patrón, ese es tu producto de suscripción y esa es la frecuencia." },
      { h: "Qué productos la tienen", p: "Lo que se consume y se termina: café, suplementos, alimento para mascotas, cosmética, yerba, productos de limpieza, pañales. Lo que se compra una vez no." },
      { h: "De recompra a suscripción", p: "La diferencia es una sola: el cobro. Con la suscripción, Mercado Pago cobra cada período y el pedido se crea solo. El cliente deja de decidir cada vez." },
      { h: "Lo que cambia en el negocio", p: "Ingresos previsibles, menos pauta para volver a ganar al mismo cliente y un ticket promedio más alto por los packs. Las tiendas con Recurrentes ven hasta un 40% de los pedidos del mes entrando solos." },
    ],
    faq: [
      ["¿Cuánto descuento hay que dar?", "Entre 10% y 15% suele alcanzar. El cliente paga menos y vos ahorrás la pauta de volver a venderle."],
      ["¿Hace falta cambiar de tienda o de pasarela?", "No. Recurrentes funciona con tu Shopify o Tiendanube y con tu cuenta de Mercado Pago."],
      ["¿Cómo empiezo?", "Con una demo de 15 minutos: vemos tu catálogo y qué productos van primero."],
    ],
  },

  {
    slug: "opciones-suscripciones-ecommerce-argentina",
    eyebrow: "Guía 2026",
    title: "Las 5 opciones para vender por suscripción en tu ecommerce en Argentina (2026) | Recurrentes",
    description: "Puentify, Orquesty, Reval, Recharge y Recurrentes: qué hace bien cada uno, cuánto cobra, en qué plataforma funciona y cómo elegir. Con datos públicos y sin vueltas.",
    h1: "Opciones para vender por suscripción en tu ecommerce en Argentina",
    intro: "Hay cinco herramientas serias para cobrar suscripciones en una tienda online argentina. Ninguna es mala: cada una está pensada para un tipo de tienda. Acá va qué hace bien cada una, cuánto cobra y cómo se comparan, con los datos públicos de cada sitio.",
    imagen: "/landing/panel-suscripciones.jpg", imagenLabel: "recurrentesapp.com · Suscripciones",
    bloques: [
      { h: "Puentify · para arrancar sin abono", p: "App argentina para Shopify y Tiendanube con Mercado Pago. Sin abono mensual: cobra un porcentaje de cada venta (2%, según comercios que lo usan; no está publicado). Bueno para probar con poco volumen; cuando la suscripción crece, el porcentaje pesa. Sin packs con variantes, sin mails con tu marca ni WhatsApp." },
      { h: "Orquesty · para Shopify con acompañamiento", p: "Plataforma latinoamericana solo para Shopify, con Mercado Pago, portal del suscriptor, bundles y una implementación guiada por su equipo. USD 79 a 229 por mes más 1% a 2% de las ventas por suscripción. Mails vía Klaviyo o Mailchimp." },
      { h: "Reval · el veterano en Shopify", p: "De los primeros en cobrar suscripciones con Mercado Pago en Shopify. USD 99 a 249 por mes más 1,2% a 1,8% de todo lo que cobrás. No funciona en Tiendanube y no permite variantes ni dos productos con suscripción en el mismo carrito." },
      { h: "Recharge · la referencia mundial", p: "La app más completa del ecosistema Shopify, pensada para Estados Unidos y Europa. USD 99 a 499 por mes más 1,49% + USD 0,19 por transacción. No cobra con Mercado Pago y los mails salen en inglés: desde Argentina, difícil." },
      { h: "Recurrentes · hecho para el ecommerce argentino", p: "Shopify y Tiendanube con Mercado Pago. Abono fijo por suscriptores activos, gratis hasta 10 y Comisión más baja que la de afuera. Packs con regalos, variantes, widget y checkout con tu marca, mails propios, recupero de carritos por WhatsApp y portal del cliente. La puesta en marcha la hacemos nosotros: pago único de USD 100 a 200, según lo que haya que armar." },
      { h: "Cómo elegir", p: "Cuatro preguntas deciden: ¿cobra comisión por venta además del abono? ¿funciona en tu plataforma? ¿soporta packs y variantes o solo un producto suelto? ¿la orden se crea sola en tu tienda? Hacé la cuenta con tu facturación real a 12 meses, no con la del primer mes." },
    ],
    vs: { titulo: "Las cinco, lado a lado", intro: "Datos públicos de cada sitio (verificados en septiembre de 2026). Lo que una herramienta no documenta, no lo inventamos.", nombre: "Puentify · Orquesty · Reval · Recharge", fuente: "Fuentes: puentify.app, orquesty.com, appreval.com, getrecharge.com/pricing. El setup y la comisión de Puentify salen de comercios que trabajan con ellos. Los precios los pone cada empresa y pueden cambiar.", filas: [
      ["Precio del plan", "<b>US$ 99 + comisión</b><small>después desde USD 99/mes</small>", "Puentify: sin abono · Orquesty: USD 79–229 · Reval: USD 99–249 · Recharge: USD 99–499"],
      ["Comisión sobre cada venta", "<b>0%</b>", "Puentify: 2% · Orquesty: 1–2% · Reval: 1,2–1,8% · Recharge: 1,49% + USD 0,19"],
      ["Cobra con Mercado Pago", "✓ Sí", "Puentify, Orquesty y Reval sí · Recharge no"],
      ["Funciona en Tiendanube", "✓ Sí", "Solo Puentify · Orquesty, Reval y Recharge no"],
      ["Variantes y dos productos en el carrito", "✓ Sí", "Recharge sí · Orquesty bundles · Puentify y Reval no"],
      ["Mails con tu marca", "✓ Sí, incluidos", "Reval sí · Recharge en inglés · Orquesty vía Klaviyo · Puentify no"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "Ninguno lo documenta"],
      ["Soporte en español por WhatsApp", "✓ Sí", "Puentify, Orquesty y Reval sí · Recharge no"],
    ] },
    faq: [
      ["¿Cuál es la más barata?", "Con muy poco volumen, Puentify (sin abono). A partir de unas decenas de suscriptores, Recurrentes: abono fijo y 0% por venta. Hacé la cuenta con tu facturación real."],
      ["¿Cuál funciona en Tiendanube?", "Puentify y Recurrentes. Orquesty, Reval y Recharge son solo Shopify."],
      ["¿Puedo cambiar de herramienta después?", "Sí, pero las suscripciones activas se vuelven a dar de alta con cada cliente porque la tarjeta la guarda cada plataforma en Mercado Pago. Conviene elegir bien al principio."],
      ["¿Y la suscripción nativa de Tiendanube?", "Existe, pero solo con Pago Nube y tarjeta de crédito, plan Impulso o superior, sin variantes y un producto con suscripción por carrito. Para muchas tiendas queda corta."],
    ],
  },
  {
    slug: "suscripcion-de-yerba-mate",
    seccion: "rubros", fecha: "2026-09-27",
    eyebrow: "Yerba mate",
    title: "Cómo vender yerba mate por suscripción en tu tienda online (Argentina) | Recurrentes",
    description: "Yerba por suscripción: el kilo que llega todos los meses, packs de 1, 2 o 4, descuento por suscribirse y cobro automático con Mercado Pago en Shopify o Tiendanube. Cómo lo arman las marcas de yerba.",
    h1: "Yerba que llega sola, todos los meses",
    intro: "La yerba es consumo diario y compra repetida: el argentino promedio toma más de 6 kilos por año. Es el producto ideal para la suscripción, y las marcas que la venden online ya lo saben. Así se arma con Recurrentes, en Shopify o Tiendanube, cobrando con Mercado Pago.",
    imagen: "/landing/prod-mate.jpg", imagenLabel: "Yerba · pack por suscripción", imagenFoto: true,
    bloques: [
      { h: "Packs por kilos", p: "1 kg por mes para el que toma solo, 2 kg para la casa, 4 kg para la oficina. Cada pack con su precio y su descuento por suscribirse. El cliente los ve como tarjetas dentro de la ficha del producto, con lo que ahorra en cada envío." },
      { h: "Con palo, sin palo, saborizada", p: "El cliente se suscribe a la variante exacta. Cada cobro crea el pedido en tu tienda con esa variante, así el depósito arma la caja sin preguntar." },
      { h: "Frecuencia según consumo", p: "Cada 30 días es lo más común, pero hay marcas que ofrecen cada 15 (matero intenso) o cada 60 (el que compra 4 kg). La frecuencia es una configuración del plan, no un desarrollo." },
      { h: "El regalo que fideliza", p: "Un pack de yuyos, una bombilla o un mate en el primer envío convierte más que un descuento extra. Los regalos viajan en la orden a $0 y se muestran en el widget con la etiqueta de regalo." },
      { h: "Recupero por WhatsApp", p: "El que llegó al checkout y no pagó recibe un WhatsApp con el link para terminar. En yerba, donde el ticket es bajo y la decisión rápida, recupera entre 1 de cada 5 y 1 de cada 4 carritos." },
      { h: "Sin comisión por venta", p: "Con ticket bajo, una comisión del 1% al 2% sobre cada cobro se come el margen. Recurrentes cobra un abono fijo por suscriptores activos y 0% por venta: gratis hasta 10 suscriptores." },
    ],
    capturas: [["/landing/panel-planes.jpg", "Planes"], ["/landing/panel-widget.jpg", "Widget"], ["/landing/panel-cobros.jpg", "Cobros"]],
    faq: [
      ["¿Funciona en Tiendanube?", "Sí. Recurrentes es de las pocas herramientas que cobra suscripciones con Mercado Pago tanto en Shopify como en Tiendanube. La suscripción nativa de Tiendanube existe pero solo con Pago Nube, sin variantes y con un producto por carrito."],
      ["¿Qué descuento conviene en yerba?", "Entre 10% y 15% por suscribirse. Como el margen es chico, conviene compensarlo con el pack de 2 o 4 kilos, donde el envío por kilo baja mucho."],
      ["¿El cliente puede pausar en verano?", "Sí, desde su portal: pausa un mes, cambia la dirección o cancela, sin escribirte."],
      ["¿Y el envío?", "Se cotiza en el checkout con los correos que ya tenés conectados (Andreani, Correo Argentino, OCA, etc.), con tus reglas de envío gratis."],
    ],
  },
  {
    slug: "club-de-vinos-por-suscripcion",
    seccion: "rubros", fecha: "2026-09-27",
    eyebrow: "Club de vinos",
    title: "Cómo armar un club de vinos por suscripción en tu tienda online | Recurrentes",
    description: "Club de vinos con cobro mensual automático por Mercado Pago: cajas de 2, 3 o 6 botellas, selección del mes, descuento de socio y la orden creada en tu Shopify o Tiendanube. Guía para bodegas y vinotecas.",
    h1: "Un club de vinos que se cobra solo",
    intro: "El club de vinos es la suscripción más antigua del ecommerce argentino y la que más margen deja: ticket alto, cliente fiel y envío planificado. Lo que suele fallar es la operación: cobrar cada mes a mano, perseguir tarjetas vencidas y cargar los pedidos. Eso es exactamente lo que Recurrentes automatiza.",
    imagen: "/landing/panel-planes.jpg", imagenLabel: "recurrentesapp.com · Planes",
    bloques: [
      { h: "Cajas como packs", p: "Caja de 2, 3 o 6 botellas, cada una con precio de socio. El descuento del club (15% a 20% es lo habitual) queda visible en el widget frente al precio de la tienda." },
      { h: "La selección del mes", p: "El plan apunta a un producto 'Caja del club'; cada mes cambiás qué botellas van dentro sin tocar las suscripciones. El cobro crea la orden con ese producto y vos armás la caja." },
      { h: "Cobro el mismo día, todos los meses", p: "Mercado Pago debita la tarjeta en la fecha del alta. Si rechaza, Recurrentes reintenta y le avisa al socio por mail y WhatsApp con el link para actualizar la tarjeta. Nada de planillas." },
      { h: "Mayores de 18", p: "El checkout pide DNI y podés sumar la casilla de mayoría de edad en las políticas del checkout, con tu texto." },
      { h: "Pausar el mes que viajan", p: "El socio pausa desde su portal y retoma cuando quiere. Es lo que más baja la baja definitiva en clubes: el que puede pausar, no cancela." },
      { h: "Landing propia del club", p: "Además del widget en la ficha, armamos una página de suscripción con tu marca: beneficios, cajas, preguntas. Como la tienda de ejemplo Tostado, pero de vinos." },
    ],
    capturas: [["/landing/panel-suscripciones.jpg", "Suscripciones"], ["/landing/panel-retencion.jpg", "Retención"], ["/landing/panel-portal.jpg", "Portal del socio"]],
    faq: [
      ["¿Puedo cobrar cada dos meses?", "Sí. La frecuencia es por plan: 30, 60 o 90 días, o cada 1, 2 o 3 meses."],
      ["¿Sirve para bodega y para vinoteca?", "Para las dos. La bodega vende su propia línea; la vinoteca arma la selección del mes con distintas etiquetas. En ambos casos la orden aparece en la tienda como un pedido común."],
      ["¿Cómo manejo el stock de la caja del mes?", "El producto 'Caja del club' tiene su stock en tu tienda como cualquier otro. Cada cobro descuenta una unidad."],
      ["¿Qué pasa si un socio no paga?", "Mercado Pago reintenta; si sigue rechazando, la suscripción queda como 'pago rechazado', el socio recibe el aviso con el link para cambiar la tarjeta y vos lo ves en el panel."],
    ],
  },
  {
    slug: "como-reducir-el-churn-suscripciones",
    seccion: "guias", fecha: "2026-09-27",
    eyebrow: "Retención",
    title: "Cómo reducir el churn de tu suscripción: 7 prácticas que funcionan en Argentina | Recurrentes",
    description: "Pausar en vez de cancelar, recuperar tarjetas rechazadas, avisar antes del cobro, packs con regalo y portal del cliente: las prácticas que más bajan la cancelación en suscripciones de ecommerce, con datos de tiendas argentinas.",
    h1: "Menos bajas: cómo retener a tus suscriptores",
    intro: "El churn (la tasa de cancelación mensual) decide si una suscripción crece o se estanca. Con 5% mensual perdés la mitad de la base en un año; con 2% la retenés casi entera. La buena noticia: la mayoría de las bajas no son por el producto, son por fricción y por tarjetas. Y eso se arregla.",
    imagen: "/landing/panel-retencion.jpg", imagenLabel: "recurrentesapp.com · Retención",
    bloques: [
      { h: "1 · Ofrecer pausa antes de cancelar", p: "Cuando el cliente toca 'Cancelar', el portal le propone pausar uno o dos meses o cambiar la frecuencia. Entre un tercio y la mitad elige pausar en vez de irse. Recurrentes lo hace solo, con tus textos." },
      { h: "2 · Recuperar la tarjeta rechazada", p: "La causa número uno de baja involuntaria es la tarjeta vencida o sin límite. Mercado Pago reintenta, y Recurrentes le manda al cliente mail y WhatsApp con el link para actualizarla. Lo que se recupera acá es plata que ya estaba perdida." },
      { h: "3 · Avisar antes del cobro", p: "Un mail o WhatsApp 3 días antes con el monto y la fecha baja los reclamos y los contracargos. El cliente que sabe que le van a cobrar no llama al banco." },
      { h: "4 · Dejar que el cliente maneje su suscripción", p: "Cambiar dirección, fecha o pausar sin escribirte. Cada mensaje de soporte que se evita es una baja que no ocurre por cansancio." },
      { h: "5 · El descuento tiene que verse", p: "El precio de suscripción con el precio de tienda tachado al lado, y 'Ahorrás $X en cada envío' debajo del botón. Si el beneficio no se ve, la primera duda es la baja." },
      { h: "6 · Regalos y packs", p: "Un regalo en el primer envío y packs de 2 o 4 unidades con mejor precio por unidad suben el ticket y la permanencia: el que se suscribió al pack grande se queda más." },
      { h: "7 · Medir por cohorte", p: "Mirá cuántos de los que se suscribieron en un mes siguen activos a los 3 y 6 meses. Analíticas de Recurrentes lo muestra por plan, para saber qué producto retiene y cuál no." },
    ],
    capturas: [["/landing/panel-retencion.jpg", "Retención"], ["/landing/panel-flujos-whatsapp.jpg", "Flujos de WhatsApp"], ["/landing/panel-analiticas.jpg", "Analíticas"]],
    faq: [
      ["¿Qué churn es normal en ecommerce?", "Entre 3% y 6% mensual en productos de consumo. Por debajo de 3% es muy bueno. Café, yerba y suplementos suelen retener mejor que cosmética."],
      ["¿La pausa no es una cancelación disfrazada?", "En parte. Pero entre la mitad y dos tercios de los que pausan retoman, y los que no, se habrían ido igual. Es plata que sin la pausa no existía."],
      ["¿Cuánto se recupera de tarjetas rechazadas?", "Con reintentos más aviso por mail y WhatsApp, entre un tercio y la mitad de los rechazos vuelven a cobrarse dentro del mes."],
      ["¿Recurrentes hace todo esto solo?", "Sí: pausa con oferta de retención, reintentos, avisos previos, portal del cliente, packs con regalo y analíticas por cohorte vienen incluidos en todos los planes."],
    ],
  },
  {
    slug: "tiendanube-suscripciones-nativas-vs-app",
    seccion: "plataformas", fecha: "2026-09-27",
    eyebrow: "Tiendanube",
    title: "Suscripciones nativas de Tiendanube vs una app: qué conviene (2026) | Recurrentes",
    description: "Tiendanube tiene suscripciones nativas, pero solo con Pago Nube, tarjeta de crédito, sin variantes y un producto por carrito. Cuándo alcanzan, cuándo no, y qué suma una app como Recurrentes con Mercado Pago.",
    h1: "Suscripciones en Tiendanube: la nativa o una app",
    intro: "Desde 2025 Tiendanube permite vender por suscripción sin instalar nada. Para muchas tiendas alcanza; para otras se queda corta rápido. Acá va qué hace cada opción, con los datos públicos de Tiendanube, para que decidas con la tuya.",
    imagen: "/landing/panel-suscripciones.jpg", imagenLabel: "recurrentesapp.com · Suscripciones",
    bloques: [
      { h: "Lo bueno de la nativa", p: "Está integrada, no cuesta aparte y se configura desde el mismo panel de Tiendanube. Si vendés un solo producto sin variantes, cobrás con Pago Nube y tu plan es Impulso o superior, es el camino más corto." },
      { h: "Dónde se queda corta", p: "Solo cobra con Pago Nube y tarjeta de crédito (sin débito ni dinero en cuenta de Mercado Pago), no soporta variantes (talle, aroma, molienda), permite un producto con suscripción por carrito y no tiene packs, regalos, portal del cliente ni recupero por WhatsApp." },
      { h: "Lo que suma una app", p: "Cobrar con Mercado Pago (crédito, débito y dinero en cuenta), packs de 2, 3 o 4 con precio propio, variantes, regalos, widget y checkout con tu marca, mails y WhatsApp automáticos, portal para pausar o cambiar la dirección, y analíticas de retención." },
      { h: "La orden sigue siendo tuya", p: "Con Recurrentes cada cobro crea el pedido pago en tu Tiendanube, con el producto, la variante y la dirección. Facturación, envíos y stock siguen funcionando como con cualquier venta." },
      { h: "Cuánto cuesta cada camino", p: "La nativa no tiene costo aparte del plan de Tiendanube y la comisión de Pago Nube. Recurrentes es gratis hasta 10 suscriptores activos y después un abono fijo por tramo, con una comisión que baja cuando crecés; la puesta en marcha la hacemos nosotros por un pago único de USD 100 a 200, según lo que haya que armar." },
      { h: "Cómo decidir", p: "Si tenés variantes, querés packs o cobrar con Mercado Pago, la nativa no te sirve. Si vendés un solo producto suelto con Pago Nube y no necesitás retención automática, probá la nativa primero: cambiar después es posible, pero cada cliente tiene que volver a suscribirse." },
    ],
    vs: { titulo: "Tiendanube nativa y Recurrentes, lado a lado", intro: "Datos del centro de ayuda de Tiendanube (septiembre de 2026). Lo que no está documentado, no lo inventamos.", nombre: "Suscripción nativa de Tiendanube", fuente: "Fuente: ayuda.tiendanube.com, 'Cómo vender productos por suscripción en Tiendanube'.", filas: [
      ["Pasarela", "<b>Mercado Pago</b><small>crédito, débito y dinero en cuenta</small>", "Solo Pago Nube, tarjeta de crédito"],
      ["Plan de Tiendanube requerido", "Cualquiera", "Impulso o superior"],
      ["Variantes (talle, aroma, molienda)", "✓ Sí", "No"],
      ["Packs y regalos", "✓ Sí", "No"],
      ["Dos productos con suscripción en el carrito", "✓ Sí", "No, uno por carrito"],
      ["Portal del cliente (pausar, dirección)", "✓ Sí", "No documentado"],
      ["Recupero de carritos y avisos por WhatsApp", "✓ Sí", "No"],
      ["Costo", "US$ 99 por mes + una comisión que baja", "Incluida en el plan"],
    ] },
    faq: [
      ["¿Puedo tener las dos a la vez?", "No conviene: el cliente vería dos formas de suscribirse en la misma tienda. Elegí una."],
      ["¿Recurrentes reemplaza el checkout de Tiendanube?", "Solo para la suscripción: el cliente completa la suscripción en el checkout de Recurrentes con tu marca y después cada cobro crea el pedido en Tiendanube. Las compras únicas siguen por el checkout de Tiendanube."],
      ["¿Necesito saber programar?", "No. La instalación la hacemos nosotros: se conecta la app desde la tienda de aplicaciones de Tiendanube y el widget aparece en la ficha del producto."],
    ],
  },
  {
    slug: "pago-rechazado-suscripcion-que-hacer",
    seccion: "guias", fecha: "2026-09-27",
    eyebrow: "Cobros",
    title: "Pago rechazado en una suscripción: qué pasa y cómo recuperarlo (Mercado Pago) | Recurrentes",
    description: "Tarjeta vencida, sin límite o dada de baja: por qué Mercado Pago rechaza un cobro recurrente, cuántas veces reintenta y cómo avisar al cliente por mail y WhatsApp para que actualice la tarjeta sin perder la suscripción.",
    h1: "Cuando Mercado Pago rechaza el cobro de una suscripción",
    intro: "En una base de suscriptores sana, entre 5% y 10% de los cobros del mes rechazan. No es un problema del producto: son tarjetas vencidas, límites agotados o bancos que frenan el débito. Lo que separa una suscripción que crece de una que sangra es qué pasa en las 72 horas siguientes.",
    imagen: "/landing/panel-cobros.jpg", imagenLabel: "recurrentesapp.com · Cobros",
    bloques: [
      { h: "Por qué rechaza", p: "Las causas más comunes: tarjeta vencida o reemplazada por el banco, límite del mes agotado (muy común los primeros días), fondos insuficientes en débito, y el antifraude del banco que frena un débito automático nuevo. Casi ninguna es una decisión del cliente." },
      { h: "Qué hace Mercado Pago", p: "Reintenta el débito varias veces durante los días siguientes. Si todos fallan, la suscripción queda pausada por falta de pago. Sin nadie que avise al cliente, ahí termina la relación." },
      { h: "Qué hace Recurrentes", p: "Marca la suscripción como 'pago rechazado' en tu panel, le manda al cliente un mail y un WhatsApp con el motivo en palabras simples y un link para cambiar la tarjeta, y le avisa a vos. Cuando el cobro entra, crea el pedido en tu tienda como siempre." },
      { h: "El link para cambiar la tarjeta", p: "El cliente entra al portal desde el mensaje, carga la tarjeta nueva y la suscripción sigue con la misma fecha. No tiene que suscribirse de nuevo ni escribirte." },
      { h: "Cuánto se recupera", p: "Con aviso por mail y WhatsApp dentro de las primeras 24 horas, entre un tercio y la mitad de los rechazos se cobran dentro del mes. Sin aviso, casi nada." },
      { h: "Prevenir: avisar antes del cobro", p: "Un mensaje 3 días antes con el monto y la fecha hace que el cliente tenga saldo y no frene el débito. Es un flujo que se prende con un clic." },
    ],
    capturas: [["/landing/panel-cobros.jpg", "Cobros"], ["/landing/panel-flujos-email.jpg", "Flujos de email"], ["/landing/panel-suscripciones.jpg", "Suscripciones"]],
    faq: [
      ["¿El cliente pierde la suscripción si rechaza?", "No. Queda como 'pago rechazado' hasta que actualiza la tarjeta o hasta que la cancela. Vos ves cuántos hay en ese estado en el panel."],
      ["¿Le cobran al cliente dos veces si reintenta?", "No. Cada período tiene un solo cobro; los reintentos son del mismo cobro."],
      ["¿Se puede cobrar con débito y dinero en cuenta?", "Sí, con Mercado Pago. El débito rechaza más por fondos; el crédito más por límite. Ofrecer los dos baja el rechazo total."],
      ["¿Qué pasa con los pedidos de los meses rechazados?", "No se crean: sin cobro no hay orden. Cuando el cobro entra, se crea el pedido de ese período."],
    ],
  },
  {
    slug: "suscripciones-shopify-sin-shopify-plus",
    seccion: "plataformas", fecha: "2026-09-27",
    eyebrow: "Shopify",
    title: "Suscripciones en Shopify sin Shopify Plus ni Shopify Payments (Argentina) | Recurrentes",
    description: "En Argentina no hay Shopify Payments y las apps de suscripción de la App Store no cobran con Mercado Pago. Cómo vender por suscripción en Shopify con el plan Basic, cobrando en pesos, con la orden creada en tu tienda.",
    h1: "Suscripciones en Shopify sin Shopify Plus",
    intro: "Las suscripciones nativas de Shopify dependen de Shopify Payments, que no existe en Argentina. Por eso Recharge, Appstle o Seal no cobran en pesos acá. La salida es cobrar con Mercado Pago fuera del checkout de Shopify y crear la orden por API. Funciona con cualquier plan, Basic incluido.",
    imagen: "/landing/panel-widget.jpg", imagenLabel: "recurrentesapp.com · Widget",
    bloques: [
      { h: "Por qué las apps de la App Store no sirven acá", p: "Todas usan la API de suscripciones de Shopify, que exige Shopify Payments o una pasarela habilitada para 'subscriptions'. Mercado Pago no lo está. Instalás la app, y al pagar el cliente no puede." },
      { h: "Cómo lo resuelve Recurrentes", p: "El widget aparece en la ficha del producto con el toggle Compra única / Suscripción. En suscripción, el cliente completa un checkout con tu marca y paga con Mercado Pago (tarjeta adentro del checkout o con su cuenta). Cada cobro crea la orden paga en Shopify." },
      { h: "Con el plan Basic", p: "No hace falta Plus ni cambiar de plan. Se conecta con una app propia de tu tienda (te guiamos) y un snippet en el tema, que instalamos nosotros." },
      { h: "La compra única no cambia", p: "El botón Agregar al carrito de tu tema, Shop Pay y las apps de bundles siguen como están. El widget solo maneja la suscripción." },
      { h: "Órdenes de verdad", p: "Cada cobro es un pedido pago en Shopify con producto, variante, dirección y la etiqueta RECURRENTE: facturación, envíos y stock funcionan igual que con cualquier venta." },
      { h: "Lo que no hacemos", p: "No cobramos comisión por venta y no guardamos tarjetas: las guarda Mercado Pago. Tampoco reemplazamos el checkout de Shopify para las compras únicas." },
    ],
    capturas: [["/landing/panel-widget.jpg", "Widget"], ["/landing/panel-checkout.jpg", "Checkout"], ["/landing/panel-cobros.jpg", "Cobros"]],
    faq: [
      ["¿Shopify lo permite?", "Crear órdenes por API y cobrar con una pasarela externa es parte de la API pública de Shopify. Es lo que hacen todas las herramientas de suscripción con Mercado Pago en Argentina."],
      ["¿Funciona con temas como Dawn u Horizon?", "Sí. El widget se adapta al tema y esconde el selector de cantidad nativo o el de una app de bundles mientras está en modo suscripción."],
      ["¿Y si después me paso a Tiendanube?", "Recurrentes funciona en las dos. Las suscripciones activas igual hay que volver a darlas de alta porque la tarjeta la guarda Mercado Pago atada a la tienda."],
    ],
  },
];
